/*

ALUNO: LUCAS DA SILVA MOUTINHO - 15/0015747
PROFESSOR: ALCHIERI
ESTUDO DIRIGIDO 4 - PROGRAMAÇÃO CONCORRENTE - 2/2018
PROBLEMA DOS CANIBAIS - O COZINHEIRO TEM QUE PREPARAR 10 PORÇÕES DE COMIDA PROS CANIBAIS.
QUANDO O COZINHEIRO PREPARAR AS 10 PORÇÕES ELE PARA DE COZINHAR. OS CANIBAIS COMEÇAM A COMER
AS PORÇÕES, QUANDO ELAS CHEGAREM A 0 ELES DEVEM PARAR DE COMER. DEVEM EXISTIR VARIÁVEIS CONDICIONAIS
DE PARADA

PSEUDOCÓDIGO:

INT COMIDA = 0;
PTHREAD_MUTEX L = PTHREAD...

COZINHEIRO {1} {

}

CANIBAIS C {1 .. N}
  WHILE(TRUE){

  }
*/